# Generated by Django 5.2.5 on 2025-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colonias',
            fields=[
                ('idColonia', models.AutoField(primary_key=True, serialize=False)),
                ('cColonia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('cEstado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('cMunicipio', models.CharField(max_length=20)),
            ],
        ),
    ]
