# Generated by Django 5.2.5 on 2025-08-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pagos', '0002_informacionpagos_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='colonias',
            fields=[
                ('idColonia', models.AutoField(primary_key=True, serialize=False)),
                ('cColonia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('cEstado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('cMunicipio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('cCalle', models.CharField(max_length=20)),
                ('cNumero', models.CharField(max_length=3, null=True)),
                ('idColonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.colonias')),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.estados')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.municipios')),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cNombre', models.CharField(max_length=30)),
                ('cApellidoPaterno', models.CharField(max_length=30)),
                ('cApellidoMaterno', models.CharField(max_length=30)),
                ('cAlias', models.CharField(blank=True, max_length=11, null=True)),
                ('cDetalle', models.CharField(blank=True, max_length=15, null=True)),
                ('idInfoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos')),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.direcciones')),
            ],
        ),
    ]
