# Generated by Django 5.2.5 on 2025-08-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('cCalle', models.CharField(max_length=20)),
                ('cNumero', models.CharField(max_length=3, null=True)),
                ('estados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.estados')),
                ('idColonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.colonias')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.municipios')),
            ],
        ),
    ]
