# Generated by Django 5.2.5 on 2025-08-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadosPagos',
            fields=[
                ('idEstadoPago', models.AutoField(primary_key=True, serialize=False)),
                ('cEstadoPago', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='estatusPagos',
            fields=[
                ('idEstatusPago', models.AutoField(primary_key=True, serialize=False)),
                ('cEstatusPago', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='informacionPagos',
            fields=[
                ('idInfoPago', models.AutoField(primary_key=True, serialize=False)),
                ('iRferencia', models.IntegerField()),
                ('iImporte', models.IntegerField(blank=True, null=True)),
                ('dFechaCorte', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('dFechaPago', models.DateField()),
                ('idEstadoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.estadospagos')),
                ('idEstatusPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.estatuspagos')),
                ('idInfoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.informacionpagos')),
            ],
        ),
    ]
