# Generated by Django 5.2.5 on 2025-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadosPagos',
            fields=[
                ('idEstadoPago', models.AutoField(primary_key=True, serialize=False)),
                ('cEstadoPago', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='estatusPagos',
            fields=[
                ('idEstatusPago', models.AutoField(primary_key=True, serialize=False)),
                ('cEstatusPago', models.CharField(max_length=9)),
            ],
        ),
    ]
