# Generated by Django 5.2.5 on 2025-08-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacionPagos',
            fields=[
                ('idInfoPago', models.AutoField(primary_key=True, serialize=False)),
                ('iRferencia', models.IntegerField()),
                ('iImporte', models.IntegerField(blank=True, null=True)),
                ('dFechaCorte', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('dFechaPago', models.DateField()),
                ('idEstadoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.estadospagos')),
                ('idEstatusPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.estatuspagos')),
                ('idInfoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.informacionpagos')),
            ],
        ),
    ]
