# Generated by Django 5.2.5 on 2025-08-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_customuser_idsucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idTipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tiposusuarios'),
        ),
    ]
